### ISSUE TITLE
GET / redirects to /menu

### ISSUE THREAD

**Issue by jgraichen** [openmensa/openmensa#15]
When manually open https://openmensa.org/ (already logged in) I get redirect to `/menu`. But not when clicking the header link.

@mswart Is this redirect intended?

**Comment by mswart** [comment]
Yes, there are even tests for that.

If a manually open openmensa.org I will most likely look which meals my interested canteens have today. So if the user has favorites, he this redirected to the menu page to see all the meals that are served today.

But as the user still might want to open the startpage, in any other case we do nothing special and render the start page.

What would be your expected behavior?
