### ISSUE TITLE
Canteen with null coordinates

### ISSUE THREAD

**Issue by domoritz** [openmensa/openmensa#3]
http://openmensa.org/api/v2/canteens?limit=50&page=4 currently returns

```js
{
  id: 192,
  name: "Gebze Yüksek Teknoloji Enstitüsü",
  city: "Gebze/Kocaeli",
  address: "Gebze Yüksek Teknoloji Enstitüsü Rektörlüğü P.K141 41400 Gebze/KOCAELİ",
  coordinates: [
    null,
    null
  ]
},
```

This crashes clients. See https://github.com/domoritz/open-mensa-android/issues/25

**Comment by cyroxx** [comment]
Is there any way to get this fixed?

**Comment by kaifabian** [comment]
As i see it, this is a specification problem: We have not yet specified how the API behaves if no coordinates are supplied for a canteen.

There are four ways to solve the problem:
A. Defining given behavior as intended and adding it to the documentation. Apps relying on a different behavior will have to be fixed.
B. Defining the coordinates field to be null (not a list of [null, null, ]) when no coordinates are supplied. This will most likely cause the same problems as variant A.
C. Removing the "coordinates" field from the response completely if coordinates are missing. Same problem as A. and B.
D. Not giving access to canteens without coordinates over the REST API. We could then inform all feed providers who provide feeds for canteens without coordinates that they are excluded from our platform until they supply coordinates.

I - personally - tend to variant B, because it best describes the situation: We know the canteen, but we do not have coordinates for it. It then is responsibility of the app to act accordingly. Any opinions on that?

**Comment by jgraichen** [comment]
There also is access to the canteen (except complete URL) via the web interface as there is no pointer on the map.

I tend to variant D as every other canteen has coordinates (afaik) and possibly add a publishing workflow for a canteen where a canteen does not appear in all public lists right after being created. Having coordinates would be a prerequisite for "publishing" together with having an actual feed URL (which also isn't the case with the canteen above). At least one successful fetch of meal data could be included too.

**Comment by domoritz** [comment]
I agree with @jgraichen. I think requiring a location is a valid requirement for open mensa. The current web interface as well as the app don't really work if the canteen has no location.

**Comment by mswart** [comment]
On a long-term basis I am also for ensuring valid coordinates and a successful fetch within the canteen publish process.

But I see two issues implementing this:

1. **Reaching that point:** I will take some time to implement this - we do not have a publishing process or so at the moment and it is at the moment impossible to set unset coordinates for a canteen (and the address to lookup is one done once and may also be fail).
2. **Ensure valid coordinates:** Also I am not sure whether we will get such cases I can think about a couple of scenarios where it is difficult to get valid coordinates (especial if the canteen is once published). e.g. we know the canteen has moved, but know not yet the knew location, someone changed the coordinates to something apparently wrong.

Therefor I prefer a combined way: documenting a defined state without coordinates (variant B), but work on a process/workflow where we will not this case (often) (variant D, @jgraichen proposal).

Other solutions are using wrong coordinates for canteens (e.g. an old wrong location or only the central point of the city), or excluding this canteens from the index actions completely (start page, api).

**Comment by cmur2** [comment]
I also would appreciate every canteen having a (valid) location from a data quality point of view but I agree with @mswart that that needs time and is maybe not always achievable.

@domoritz @cyroxx the app currently does not rely on the location information? I think it'd be good to 'harden' it until we resolve the issue in one way or another.

**Comment by mswart** [comment]
If should find time tomorrow (Friday) to implement variant B (return null instead of [null, null] for unknown coordinates). 
@domoritz @cyroxx Do you want a filter to get only canteens with coordinates?

**Comment by cyroxx** [comment]
@cmur2: This hardening is already work in progress, please see domoritz/open-mensa-android#25.

@mswart: The app currently relies heavily on proper coordinates, so the best way to deal with canteens that have no coordinates set is to ignore them. As it currently stands, the spec does not mention to expect nulls anywhere in the coordinates. Depending on the solution you choose, I think it should be documented - both in the API summary page and in the Canteens page, I guess - what happens when there are no coordinates available.
If you were implying whether or not you should implement a special filter for us, I would say it is not necessary, but maybe @domoritz wants to have a word on this.

**Comment by domoritz** [comment]
I'm sure you're doing the right thing. @cyroxx I don't know exactly how the json mapping library will handle nulls but if you looked into it and it seems that making the coordinate null could be supported, great.

**Comment by mswart** [comment]
Variant B is implemented and with the new filter hasCoordinates=(true,false) deployed.
