### ISSUE TITLE
Canteens not updated anymore

### ISSUE THREAD

**Issue by Y0hy0h** [openmensa/openmensa#35]
Some canteens appear to not be updated anymore, even though their parsers appear to work fine.

See the [issue on OpenMensa Parsers](https://github.com/mswart/openmensa-parsers/issues/76#issuecomment-380749474).

# Observations
The "main" canteen for Aachen, the [Academica](http://openmensa.org/c/187), is normally displayed. However, secondary canteens, which use the same parser, e. g. [Ahorn](http://openmensa.org/c/95), have not received any updates since a while.

I do not know what differences OpenMensa sees between these parser.

**Comment by jgraichen** [comment]
It seems the Index-URL from several parsers do not return valid JSON but an empty page resulting in feeds being disabled (for example http://omfeeds.devtation.de/aachen/index.json).

This seems to only affect parsers from mswart/openmensa-parsers but from several locations. Did any recent change there broke the index pages?

**Comment by jgraichen** [comment]
The difference between Academica and the other canteens is probably because Academica is configured as a single parser not using the Index URL function but directly linking to the XML feed.

**Comment by klemens** [comment]
The [index.json](view-source:http://omfeeds.devtation.de/aachen/index.json) returns the following for me (although with the wrong mime-type):
```
{
  "bayernallee": "http://omfeeds.devtation.de/aachen/bayernallee/metadata.xml",
  "vita": "http://omfeeds.devtation.de/aachen/vita/metadata.xml",
  "ahorn": "http://omfeeds.devtation.de/aachen/ahorn/metadata.xml",
  "academica": "http://omfeeds.devtation.de/aachen/academica/metadata.xml",
  "templergraben": "http://omfeeds.devtation.de/aachen/templergraben/metadata.xml",
  "juelich": "http://omfeeds.devtation.de/aachen/juelich/metadata.xml",
  "eups": "http://omfeeds.devtation.de/aachen/eups/metadata.xml",
  "goethe": "http://omfeeds.devtation.de/aachen/goethe/metadata.xml",
  "zeltmensa": "http://omfeeds.devtation.de/aachen/zeltmensa/metadata.xml"
}
```
However, the linked metadata.xml files directly return the menu instead of some metadata. I guess we should return the proper metadata here?

I don't think that there were any recent changes in mswart/openmensa-parsers that could explain this. I am not 100% sure but I think that some time ago all parsers were configured without index urls, but I don't know why (and exactly when) this changed.

**Comment by jgraichen** [comment]
Ahh, then that was the problem. I've investigated yesterday and just tried to remember the results.

**Comment by serupp** [comment]
Are there any news about this issue. This issue is very critical for us. We run an app which is consuming the openmensa api and this feature isn't working any longer. Can we offer any help?

**Comment by jgraichen** [comment]
The nicest way would to provide the openmensa-parsers with a proper metadata.xml endpoint returning at least the feed URLs. This probably means adjusting [HandlerSource](https://github.com/mswart/openmensa-parsers/blob/master/utils.py#L164) to return a metadata.xml.

Otherwise one had to change the configuration of each effected parser on openmensa, removing the metadata URL and manually adding the feed URLs.

**Comment by jgraichen** [comment]
The parsers have been updated to include a metadata.xml endpoint. OpenMensa will update the canteen metadata early tomorrow and all effected feeds should be restored. This way we do not need to manually unconfigure all Index-URLs nor manually restore remove the metadata URL and restore the feed URLs. Everything should work again tomorrow.
