### ISSUE TITLE
API does not deliver data for canteens of Studentenwerk Dresden

### ISSUE THREAD

**Issue by bandemer** [openmensa/openmensa#830]
API Endpoint for meals of canteens in Dresden, Zittau, Görlitz and Tharandt returns 404 error
for instance: https://openmensa.org/api/v2/canteens/80/days/2024-01-08/meals

**Comment by jgraichen** [comment]
If a day does not exist (no data, no details), the API will return 404.

It seems the canteen has no data:

```console
$ curl https://openmensa.org/api/v2/canteens/80/days
[]
```

Was there anything there before?

**Comment by bandemer** [comment]
However, data should be supplied for days and meals.
The parser for Dresden works as usual and delivers the expected data, at least if you test it locally:
https://github.com/Unlifate/openmensa-parsers/tree/master
Nothing has been changed on the Studentenwerk website.
It looks as if the parser on the OpenMensa server is no longer running or has a problem.

**Comment by S60W79** [comment]
> If a day does not exist (no data, no details), the API will return 404.
> 
> It seems the canteen has no data:
> 
> ```
> $ curl https://openmensa.org/api/v2/canteens/80/days
> []
> ```
> 
> Was there anything there before?

The software seemed to work until 2024. For instance, there is still data for this request: https://openmensa.org/api/v2/canteens/80/days/2023-12-15/meals
Also the metadata (coorinates etc.) are still working.
Could the admin team please check if there is something in the server logs?
StuWe Dresden is a big Mensa provider for over 40.000 students and employees.

**Comment by jgraichen** [comment]
The server mentioned in the feed URL and the parser URL (ID: 20) are not available since December last year (TCP connect error). Maybe the parser author (@Unlifate) isn't running [Unlifate/openmensa-parsers](https://github.com/Unlifate/openmensa-parsers/tree/master?rgh-link-date=2024-01-24T15%3A46%3A36Z) anymore?

openmensa.org only is a database and does not run any parsers on its own. See https://openmensa.org/about.

If anyone else wants to host the parser, we can transfer the source ownership and/or change the feed and index URL. See details about the XML feed format on https://docs.openmensa.org/feed/v2/.

>  Could the admin team please check if there is something in the server logs?

There isn't any team, just me for the last 10 years. Any help for improvements or more collaborative canteen/parser management would be appreciated.

**Comment by Unlifate** [comment]
@jgraichen and @S60W79 . Thanks for mentioning me. Didn't notice that the server does not respond anymore. Will look into this. 
Dresden parser will be up again within the next days! Will keep you updated.

**Comment by S60W79** [comment]
Good to hear (:
Do you need any help concerning more Maintainers or Server capacities? If so, you can contact me under my Username @S60W79 in Telegram or [Wikipedia](https://de.wikipedia.org/wiki/Spezial:E-Mail_senden/S60W79). There are some facilities at TUD which might help.

Greetings

**Comment by Unlifate** [comment]
@S60W79 @jgraichen 

We are currently switching servers from private to institutional hosting. I will not further maintain the project. Studentenwerk Dresden will maintain the parser and the servers for the parser. I don't know how fast they will be, but I will keep you updated here.
Thanks for the help that you've offered.

**Comment by S60W79** [comment]
@bandemer Thank you so much for your concern to this issue 👍 
Also for you and the team, if you need help during the migration I could try to do my best or ask volunteers. We are really looking forward to seeing this working again (;

**Comment by jgraichen** [comment]
Data is already available for the canteens again.
